FROM maven:3.6.2
# 镜像挂载宿主机 docker ，执行错误while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
# 提高gitlab执行速度
RUN apt-get update && apt-get install -y libltdl7
