FROM alpine:latest


ARG KUBE_LATEST_VERSION=v1.13.6
# 构建配置文件，这个是kubectl默认执行的配置文件
RUN mkdir /root/.kube
COPY config /root/.kube/config


RUN apk add --update -t deps curl

RUN curl -L https://storage.googleapis.com/kubernetes-release/release/${KUBE_LATE
ST_VERSION}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
RUN chmod +x /usr/local/bin/kubectl

RUN apk del --purge deps

RUN rm /var/cache/apk/*
WORKDIR /root